R = 2.59;       % Winding resistance
L = 708e-6;     % Winding inductance
Kt = 79.9e-3;   % Torque constant
Ke = Kt;        % Back EMF constant
J = 1.15e-6;    % Rotor inertia
B = 1.1e-5;     % Viscous friction constant
MR = 6.5e-3;    % Coulumb friction
Kp = 2.3;
U_MAX = 12.16;
